
# Just a QUICK config setupd

data:
  data_dir: "../../Data/RTX_sorted" # Goes back 2 folders. For Ailab, change if local.
  sample_rate: 16000
  duration: 2.0                # 2 seconds like we agreed
  random_seed: 42
  label_map: {"disturbing": 0, "transient": 1, "stationary":2}

mfcc:
  n_mfcc: 39                   # How big feature vector is at each time frame
  n_fft: 512
  hop_length: 256
  duration: 2.0                # 2 seconds as we agreed on


training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.0002
  weight_decay: 0.0001
  lr_patience: 5               # plaetuehhh lr reduction lmao eat my ass
  lr_factor: 0.5
  early_stop_patience: 15
  num_workers: 4
  device: "auto"               # auto or cpu

  # for mlflow and dagshub
  repo_owner: "rasmusmolby"
  repo_name: "Audio-Classification-GRU-and-CNN"

output:
  save_dir: "./outputs"
